### ISSUE TITLE
3D 数据库

### ISSUE THREAD

**Issue by huajianxiaowanzi** [StellarCheng/Scuplt_3d#2]
请问您论文中使用的3D 数据库是哪个？

**Comment by StellarCheng** [comment]
> 请问您论文中使用的3D 数据库是哪个？

Thank you for your interest in our work. The dataset we use is T3Bench. More details about the dataset can be found on the website: https://github.com/THU-LYJ-Lab/T3Bench

**Comment by huajianxiaowanzi** [comment]
Thank you for your reply. Excellent work!

**Comment by StellarCheng** [comment]
> Thank you for your reply. Excellent work!

Thanks!
