### ISSUE TITLE
retrieval code missing

### ISSUE THREAD

**Issue by huajianxiaowanzi** [StellarCheng/Scuplt_3d#3]
Excellent work! I have two questions.
1. In the Updates section of your readme, it says "More shape retrieval and processing code is to be updated". Does the fact that the retrieval code has not been uploaded affect the running of the python run.py command?
2. If enter the text "Tiger tank", can Sculpt3D generate the corresponding 3D model.

If you could take the time to respond, I would really appreciate it!

**Comment by StellarCheng** [comment]
> Excellent work! I have two questions.
> 
> 1. In the Updates section of your readme, it says "More shape retrieval and processing code is to be updated". Does the fact that the retrieval code has not been uploaded affect the running of the python run.py command?
> 2. If enter the text "Tiger tank", can Sculpt3D generate the corresponding 3D model.
> 
> If you could take the time to respond, I would really appreciate it!

Sorry for the late reply. Actually, the run.py is not affected by the retrieval code. We can first retrieve a shape from the shape database and then run the code based on that shape.

Regarding your second question, yes, you can first use the text "Tiger tank" to retrieve a shape, and then executing run.py will produce the corresponding 3D model. I will add the retrieval code in a few days and provide more detailed guidance.

Thank you for your attention to our work!

**Comment by huajianxiaowanzi** [comment]
Thanks!!! I am very grateful!
